### ISSUE TITLE
MySQL table creation error

### ISSUE THREAD

**Issue by vrelk** [linuxserver/Heimdall#366]
I am setting up heimdall using MySQL as a backend, but it is giving the following error.
MySQL: 10.1.40-MariaDB-0ubuntu0.18.04.1 - Ubuntu 18.04
PHP: PHP 7.2.19-0ubuntu0.18.04.1
Heimdall version: 2.2.2

*****@*****:/var/www/sites/*****/html# php artisan key:generate

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_username_unique`(`username`))

In Connection.php line 458:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by KodeStar** [comment]
Never tested it with anything other than sqlite, mysql isn't mentioned anywhere as far as I know, so not really a bug. That said, it *should* work with mysql, but according to https://laravel-news.com/laravel-5-4-key-too-long-error it seems the issue is your version of mysql/mariadb is too old, so use a more up to date mariadb (10.4 appears to be the current release) and let me know if it's still an issue with that.
