### ISSUE TITLE
Autologin links not working

### ISSUE THREAD

**Issue by AndrewSav** [linuxserver/Heimdall#395]
Hello I have a problem with autologin feature. Autologins links stop working after server restart. When you click a link, you end up at Admin's (default) page not at the User's page. When you visit the appropriate User's page at least once after the server restart, the link starts working again. What am I doing wrong?

**Comment by Jamie96ITS** [comment]
Having the same issue here, though it seems to be more related to a cold browsing session rather than a server reboot. For me, to replicate, add an autologin URL to the Firefox bookmarks bar. Close Firefox. Start Firefox, click the bookmark, and end up on the public user. Click the bookmark again, end up in public again. Log in to the user, switch back to the public user, click the bookmark, and end up at the appropriate user page. Go public again, open a new tab, close the old tab. Click Bookmark, end up at the appropriate user page. Close Firefox, reopen and URL only opens public.

**Comment by guitaristtom** [comment]
Having the same issue.

How has this been an issue for two and a half years...

**Comment by Paul-SB** [comment]
Having the same issue. (Version 2.2.2)

**Comment by Openhabber** [comment]
Same. Not working.
