### ISSUE TITLE
419 error when hitting save

### ISSUE THREAD

**Issue by eisengrau** [linuxserver/Heimdall#416]
Hello,

I have followed the documentation to install Heimdall, I get a 419 error each time I click on save in settings

" 419

Sorry, your session has expired. Please refresh and try again.

"

I am using Debian Buster with PHP 7.3 and Apache, I have set .htaccess globally, installed Heimdall into the defailt www vhosts, (of course modified the servered directory to /var/www/public). /var/www/public has AllowOverride All enabled. In desperation I have chmod 777 the entire www dir/subdirs.

Thank You,

**Comment by KodeStar** [comment]
Assuming you have already run it before, maybe try another `php artisan key:generate`  which will flush the session data. The problem is this is most likely down to something in your environment that isn't quite right, or a step you may have over looked which is why the docker is easier because we don't have to guess anything about your setup. Let me know how you get on.

**Comment by stefmsft** [comment]
Well I use heimdall in docker with the linuxserver image since a week and I get the 419 almost all the time when I try to modify the settings also ... Very frustrating ... Not talking about the slowness that I had to fix because the setting of the fpm spawning mecanism was to low by default. I'd love to see if I'm alone with this problem.

**Comment by stefmsft** [comment]
Update for my previous post:
Heimdall Version 2.2.2 / Latest version of docker
No reverse proxy publishing involved
and I ve seem that it could related to the lack of @csrf in the form but I won't make such change ...

**Comment by stefmsft** [comment]
Btw, my last comment if it helps. When I use Firefox in place of Edge/Chromium it works fine. Hope it can give hints to the dev.

**Comment by thesniper710** [comment]
As a matter fact this is also hapening on the Docker version, and all of a sudden, so now, impossible to make any change,

**Comment by stefmsft** [comment]
@KodeStar , is there a way to repoen this issue and have closer look at what happen. My dunb guess is that the php settings from a fresh install are wrong. This is the purpose of docker to isolate from environment mistakes. I don't see how this wouldn't repro using the same docker image. I can give you more hints and repro if you wish.

**Comment by therner** [comment]
I was running into this issue on my own non-Docker install. I found that the log file at {HEIMDALL_INSTALL}/storage/logs/laravel.log was helpful in identifying the issue. In my case I needed to change the permissions of the {HEIMDALL_INSTALL}/storage/framework/sessions directory so that nginx was able to write to it. This obviously doesn't fix the Docker image, but hopefully it can help with at least a temporary solution to the problem.

**Comment by aptalca** [comment]
I have no such issues with docker and permissions, or saving settings. The entire heimdall folder is owned by the same user as the nginx workers. I have no idea what you guys are referring to by saying the docker image is broken.

**Comment by qy2009** [comment]
I have the same issues with 419 on docker.

**Comment by qy2009** [comment]
actually, I got it working now. 
1. Completely remove the Heimdall installation (/mnt/user/appdata/Heimdall);
2. In the docker config, user your own PID and PGUID (cannot be root);
3. Re-run the docker, and it worked :)

**Comment by Sagar-9637** [comment]
Hello,
I am working on docker i deploy my application with the help of docker but when i hit the url at that time its show my application page but its not showing captcha and if i bypass it then im not able to login in that application. and when i check in network section its showing 419 error
