### ISSUE TITLE
Requirements list incomplete

### ISSUE THREAD

**Issue by schmirgo** [linuxserver/Heimdall#479]
Hi,

i found that you also have the requirements but those ar not listed in your requirements documentation on the github site:
php7-session

Cheers

**Comment by DMunkov** [comment]
Instead of creating a separate thread, figured it's the same issue type so please forgive me for hijacking this thread.

I've spent last 3 days trying to set up Heimdall from a cloned repo, rather then using Docker container, since it is possible based on the documentation. I've progressed a bit further than I will explain in the next paragraph but I need a guidance on whether I am missing something very obvious here.

So, based on the requirements listed in the readme file, I have these following packages installed on my CentOS box:
```
- git
- nginx
- php 
- php-fpm 
- php-common  
- php-mysqlnd
- php-bcmath
- php-cli
- php-mbstring
- php-pdo
- php-xml
- php-json
- php-pecl-zip
```

Followed by these steps:
```
cd /path/to/heimdall
cp .env.example .env
php artisan key:generate
```

But I've only got the default nginx page.

**Comment by maxfarrior** [comment]
[This is working for me in a CentOS 7 LXC container.](https://gist.github.com/maxfarrior/389ea1c7f89ac0f1062835a3c4d2cc48)

Everything is run as root. Hopefully, it's clear what text goes into files, I didn't bother with the cat and heredocs.

Since PHP 7.1 is needed, I used the php-fpm service. Basically, this is a standalone ""php processor program"". I installed this and the PHP packages from the official CentOS Software Collections repo.

I used Apache, just because I'm familiar. Since I used php-fpm this setup isn't tied to Apache. You can easily configure nginx to send php files to the local php-fpm service, but I don't know how to do that off the top of my head.

The 'php artisan key:generate' command took about two minutes to run, it didn't get hung.
