### ISSUE TITLE
fontawsone icon not showing

### ISSUE THREAD

**Issue by Rar9** [linuxserver/Heimdall#569]
ubuntu 20.04 fresh docker (arm64v8) install icon is not showing of different browsers
![image](https://user-images.githubusercontent.com/2239608/111439395-9f2c5100-8705-11eb-8fdc-69ef34ce0b6d.png)

**Comment by radugrecu** [comment]
Same here
ubuntu 20.04 arm64v8

The only difference I can spot is the font-family which, in my case, is "Font Awesome\ 5 Pro"

![image](https://user-images.githubusercontent.com/6499779/116411125-134a3080-a83e-11eb-8ab5-6d96e2883ef0.png)

**Comment by itelichko** [comment]
Same on x64. Only icons added by CSS pseudo-elements are affected.

This happens because fontawesome CSS is missing, so its webfonts are not loaded. I added  ` <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.1/css/all.css" type="text/css">` in the `head` element with browser dev tools and icons in alerts appeared.

Not sure how to fix it properly. Looks like fontawesome CSS was replaced by JS version. It works by replacing styled `<i>` elements with SVG and does not use webfonts at all. Probably alerts should be changed to use `<i>` elements, like all other places. If that is too hard, returning fontawesome CSS can be a temporary workaround.

**Comment by Virepri** [comment]
A temporary personally appliable fix is to do `docker exec -it heimdall /bin/bash` and edit `/var/www/localhost/heimdall/resources/views/layouts` to add `<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.1/css/all.css" type="text/css">` to the `head` element.

You'll have to re-apply that patch every time you regenerate heimdall, though.

**Comment by KodeStar** [comment]
fixed in the soon to be released version
