### ISSUE TITLE
Badly formatted HTML after linuxserver/heimdall:latest docker image upgrade

### ISSUE THREAD

**Issue by jeffr1975** [linuxserver/Heimdall#638]
I upgraded to the latest tag of linuxserver/heimdall:latest image.  After doing so, the heimdall page load is an unformatted manner.  I need help how to troubleshoot this.  

The current home page basically just load this text with no links:

Pinned Items
app.dashboard
Router
Netdata
Gitea
Portainer
Nginx Proxy Manager
AdGuardHome
Seq
Jackett
qBittorrent
Plex
Mealie
Bookstack
Dash
Items

**Comment by lleir89** [comment]
Same here

**Comment by ldupont226** [comment]
same for me

**Comment by aptalca** [comment]
with the info provided, there is nothing we can say or do about it because it works fine over here
further messages of `same here` won't help at all other than maybe make the op feel less lonely

**Comment by boerge30** [comment]
If I run Heimdall over the IP (192.xxx.xxx.xxx:8050 in my case) then everything works fine. The run via the reverse proxy (NGINX Proxy Manager / https) is incorrect.

**Comment by lleir89** [comment]
Yeah the problem is, locally works everything ok, with (localip:8050 or localip:8443) but using Nginx Proxy Manager via https, doesn't use the full header, it puts the port that is doing reverse proxy now
![Captura de pantalla 2022-01-06 111743](https://user-images.githubusercontent.com/46818746/148367850-7a2d254c-32ae-4319-bee4-ff6bae395fca.jpg)
![Captura de pantalla 2022-01-06 111735](https://user-images.githubusercontent.com/46818746/148367857-0861fa43-c4a8-4942-b5a6-edca92b2cf81.jpg)
![Captura de pantalla 2022-01-06 111753](https://user-images.githubusercontent.com/46818746/148367858-1a8d5b6a-587d-4d98-8794-215e401d3d31.jpg)
![Captura de pantalla 2022-01-06 111748](https://user-images.githubusercontent.com/46818746/148367860-7c91c404-9ea0-4422-9448-a6b0eab58de8.jpg)
.

**Comment by tsogaard** [comment]
For those experiencing this issue on reverse proxy may be a fix curtesy of Drahakar on [unraid forums](https://forums.unraid.net/topic/68194-support-linuxserverio-heimdall/page/9/?tab=comments#comment-1080094):
 
Edit heimdall file: var/www/localhost/heimdall/.env
and change the host (APP_URL) from http://localhost to http://SUBDOMAIN.DOMAIN

Worked for me

**Comment by lleir89** [comment]
Now it's working thanks!!! It's inside the docker the problem so!

**Comment by rimclean** [comment]
same here. :-)

**Comment by top-cg** [comment]
Thanks, it also solved my issue :)

**Comment by Bmiest** [comment]
Thanks, that did the trick @tsogaard

**Comment by aptalca** [comment]
For the docker image, the `.env` file is inside the config folder under `www` and is user customizable

This is the wrong repo for reporting issues with the docker image
