### ISSUE TITLE
Apps become unpinned sporadically

### ISSUE THREAD

**Issue by boehser-enkel** [linuxserver/Heimdall#857]
Hi,
from time to time alls my apps get unpinned and i have to repin them.

Container config:
![grafik](https://user-images.githubusercontent.com/59539881/171185657-d209a4f4-08ce-4c54-bc0f-0ef0843bc2ef.png)
![grafik](https://user-images.githubusercontent.com/59539881/171185755-91496f18-2866-4ab3-88db-f4b4715a6d4c.png)
![grafik](https://user-images.githubusercontent.com/59539881/171185803-a961cc70-e11a-4ee7-b156-4616a0a3a0d1.png)
![grafik](https://user-images.githubusercontent.com/59539881/171185853-0febb8dc-7d97-4069-b9c7-656142296b03.png)
![grafik](https://user-images.githubusercontent.com/59539881/171185891-316d3f92-afad-4fc6-8242-bfd479274d65.png)
![grafik](https://user-images.githubusercontent.com/59539881/171185939-59468574-0e07-4283-a624-d67868e4d882.png)

**Comment by sawahsawah** [comment]
I am also experiencing this issue. It seems to remember all of my items, but they just randomly become unpinned. Also, the background I set disappeared at one point (I've just left it as default for now out of laziness).

**Comment by keriati** [comment]
After a lot of testing I could not reproduce any such issue.
Be aware that when you unpin an item on a tag page, it will be also unpinned on the dashboard and other tag pages. This might be changed in the future.

**Comment by Foxi352** [comment]
We had the exact same problem happen today. Heimdall running as Docker container for +/- 1 year. Not updated the image since then. While is is used on daily base by 3 people, the last modifications have been made in December.

Suddenly this morning all Pin's and our custom background disappeared. A single tile "app.dashboard" was left. I don't even know what that is or how it can be removed.

Everything was still in our application list. I had to manually repin every item and reupload the background picture. At the same time i now updated to latest docker image.

Now everything is working again, except that i can't get rid of that "app.dashboard" pin as it's not in the application list. Probably i will need to edit the sqlite database manually ?

![Screenshot 2023-01-17 at 13 51 48](https://user-images.githubusercontent.com/5746932/212906829-a3ffefaa-4ccd-4d66-8b04-3ee7e7771264.png)
![Screenshot 2023-01-17 at 13 52 12](https://user-images.githubusercontent.com/5746932/212906850-5f3387f7-e9c2-48ab-ae26-65c12772c4ca.png)

**Comment by keriati** [comment]
@Foxi352 I would suggest to edit the sqlite db to remove that app.dashboard entry. 

As there are a bunch of updates, something might have gone wrong in the migration. 

There is now an export/import feature that could also be used to backup your list of apps.

**Comment by Foxi352** [comment]
@keriati That's what i will do.

But to be clear: **The problem appeared this morning WITHOUT touching anything or doing any updates.**
Everything unpinned, background gone, mysterious app.dashboard tile appeared.

No update was done since the first installation a year ago. And the last application tile was added weeks ago. It was only used read-only since december. No one touched it or did anything to make the problems appear. Just like for the OP.

I just profited to do the update at the same time that i resolved the problem. But i did the update only BECAUSE of the problem. 

So there is definitely a, maybe rare, issue with the software. (or maybe only with docker image ?)

**Comment by boehser-enkel** [comment]
It gets unpinned. Since i disabled pinning the problem did not occur anymore

**Comment by thommo17** [comment]
I'm getting this issue at the moment too.

Sometimes it's all of the apps leaving a blank dashboard and other times it's just a few of them.

How do you disable pinning?

**Comment by boehser-enkel** [comment]
> I'm getting this issue at the moment too.
> 
> Sometimes it's all of the apps leaving a blank dashboard and other times it's just a few of them.
> 
> How do you disable pinning?

I blocked access to /items in Nginx Proxy Manager:

```
    location /items {
    }
```

**Comment by codeph0enix** [comment]
Just wanted to comment here since same behavior as above users on latest - no changes to my config files and randomly a bunch of my links became unpinned. My background also has disappeared/reverted to default.

It seems random but I am noticing in my case all apps that were unpinned used only a custom tag (not on Home Screen).  It was not all apps with only custom tags, but the ones that were unpinned all had custom tags. This happened to me a few months ago as well, just ignored it then and repinned all missing apps.

**Comment by nemsys54** [comment]
I am experiencing this as well about once a month. No changes, no edits, just a random number of items become unpinned.  I keep repining, but it occures repeatedly.  Any suggestions?

**Comment by KodeStar** [comment]
The only thing I can think is it happens when there is a new version. Because when there is an update we run migrations and seeds to ensure anything new is added in, and this is the only potential code I can find that might do something:
```
        if (! $home_tag = \App\Item::find(0)) {
            $home_tag = new \App\Item;
            $home_tag->id = 0;
            $home_tag->title = 'app.dashboard';
            $home_tag->pinned = 0;
            $home_tag->url = '';
            $home_tag->type = 1;
            $home_tag->user_id = 0;

            $home_tag->save();
            $home_tag_id = $home_tag->id;

            if ($home_tag_id != 0) {
                Log::info("Home Tag returned with id $home_tag_id from db! Changing to 0.");

                DB::update('update items set id = 0 where id = ?', [$home_tag_id]);
            }

            $homeapps = \App\Item::withoutGlobalScope('user_id')->doesntHave('parents')->get();
            foreach ($homeapps as $app) {
                if ($app->id === 0) {
                    continue;
                }
                $app->parents()->attach(0);
            }
        }
```
Basically at some point we added the dashboard category, so if it's missing, it adds it and attaches anything without a parent category to it.

It doesn't really explain the behaviour found though.

**Comment by nemsys54** [comment]
I’m not sure if this is helpful, but I did find what seemed to be a corrupt
entry. While editing entries one at a time, one of them threw an error
(possibly a 404, though I didn’t capture the exact message). I deleted that
entry and will monitor. Could a corrupt item cause this behavior?

This issue has been happening for me roughly every six weeks. Next time,
I’ll capture the error details and share them here. For context, I hadn’t
updated anything and the container had been running for over a month when
it occurred.

**Comment by afunworm** [comment]
> entry. While editing entries one at a time, one of them threw an error

I ran into this issue and not sure what to do. Without any update to the Docker image, the apps just got unpinned randomly. Then, after I pinned them back and use them for a while, they disappear again!

No changes to settings or whatever. The app just got unpinned randomly. All of them.
