### ISSUE TITLE
"Allow public access to front" is not working well for tags

### ISSUE THREAD

**Issue by tstanciu** [linuxserver/Heimdall#895]
"Allow public access to front" only works for the main dashboard. If a tag is accessed (under which are other applications), the password is requested, although it should not be. I hope I'm not wrong, but I think the password should only be required when accessing menus where data is changed (if this option is activated).

![image](https://user-images.githubusercontent.com/63559907/187097193-1eddf250-c0bd-4f97-867d-c1c8b75451bb.png)

**Comment by AleixMT** [comment]
I am havin the same issue: I was expecting that "Allow public access to front" would allow any user to access the links and tags in the dashboard without requiring authentication, but when you try to enter into a tag group to see the links the login page is prompted. I think that this is a bug and when you have the option "Allow public access to front" the login should only be prompted when modifying the settings of the dashboard, adding users, etc.

Can someone at least confirm that this is a bug and is not the intended behaviour?

**Comment by AleixMT** [comment]
I can confirm this is a bug because the behaviour is incoherent. 

Steps to reproduce the issue and see that is incoherent:
- First activate the _"Allow public access to front"_
- Create a tag and an app that is inside that tag and pin it.
- Now create an app that is in the dashboard, without any tag and pin it too. 
In my case it looks like this:

![image](https://user-images.githubusercontent.com/23342150/207941074-8b6d1d20-dcf4-4ef9-9214-1157a11711e8.png)

When I click into the "test" icon that is a simple link to google my browser shows the Google page, but when I click into "Electronic notebook", it requires a login. This is clearly wrong. The content of the tags should be accessed too without login too.

Did you find any workaround? @tstanciu I was going to put this into production but this issue is driving me crazy. 

@keriati Sorry to bother, but can you take a look into this? Seems a misconfiguration issue more than an error. If you can guide me a little into what I need to change I can raise a PR to fix this issue. 

Anyway, thank you for Heimdall, this is a wonderful software...  😄👯‍♂️
