### ISSUE TITLE
Traefik Reverse Proxy

### ISSUE THREAD

**Issue by gi8lino** [linuxserver/Heimdall#96]
I use Traefik as reverse proxy. I cannot add a URL. I get ther error: 
`Mixed Content: The page at 'https://domain.com/' was loaded over HTTPS, but requested an insecure script 'http://domain.com/js/app.js'. This request has been blocked; the content must be served over HTTPS.`
If I forward port 443 to Heimdall, I get "502 Bad Gateway".

**Comment by aptalca** [comment]
when you do port 443, also use https so it's proxied to
https://heimdall:PORT (where port is 443 or whatever you mapped that to)

**Comment by giottolino** [comment]
now I get a "500 Internal Server Error"
I set these labels:
- "traefik.enable=true"
- "traefik.frontend.rule=Host:heimdall.domain.com"
- "traefik.backend=heimdall"
- "traefik.port=443"
- "traefik.protocol=https"

PS: I run Heimdall in the official linuxserver/heimdall container...

**Comment by KodeStar** [comment]
v1.4.1 hopefully fixes a lot of reverse proxy issues, so probably worth giving that a go.

**Comment by gi8lino** [comment]
great, it works now!

**Comment by vikramgorla** [comment]
Spent a lot time of figuring out the fix, this github issue was the first hit in google.

I had the same issue and the fix was as in below ticket
[https://github.com/linuxserver/Heimdall/issues/187](https://github.com/linuxserver/Heimdall/issues/187)

Container labels for heimdall container
```
        traefik.frontend.rule:  Host:heimdall.${domain}
        traefik.port: 443
        traefik.protocol: https
```

IMPORTANT config to make this work is to add below line in traefik.toml config file as heimdall uses self signed certificates by default and it is OK behind traefik (note that this config is applied at traefik level for all backends, so know the impact if you have other container/.. backends where you dont want to trust certificates by default)

`insecureSkipVerify = true`

**Comment by KodeStar** [comment]
Thanks for adding some useful information, hopefully it will help anyone else having the same issue.

**Comment by hutch0** [comment]
I know this is an old and closed issue, but I wanted to provide updated information in case anyone else is still running into the same issue. Instead of adding insecureSkipVerify = true, which exposes trust issues with all certificates, you can pass through the https request to the container directly via tcp with Traefik now.  That way, you'll get a certificate warning and just have to accept the certificate from Linuxserver.io instead of trust every certificate that you load through Traefik. That is done with:
` 
traefik.enable=true
traefik.tcp.routers.heimdall.entrypoints=https
traefik.tcp.routers.heimdall.rule=HostSNI(`heimdall.$[domain]`)
traefik.tcp.routers.heimdall.tls.passthrough=true
traefik.tcp.routers.heimdall.service=heimdall-svc
traefik.tcp.services.heimdall-svc.loadbalancer.server.port=443
`
